### ISSUE TITLE
Update github description

### ISSUE THREAD

**Issue by nanliu** [IrekRomaniuk/snap-plugin-collector-sessioninfo#5]
When we auto generate the plugin catalog info in the snap repo, we rely on the github description field. Would you mind updating the description from 'collect Paloalto firewall session info' to 'Collects Paloalto firewall session info'

**Comment by irom77** [comment]
Done

**Comment by nanliu** [comment]
Sorry, I should make it clear, the description here (right under code tab):
<img width="614" alt="screen shot 2016-12-05 at 10 34 45 am" src="https://cloud.githubusercontent.com/assets/323624/20897274/83b42de4-bad6-11e6-99d2-d673b6ef300c.png">

**Comment by irom77** [comment]
np , done

**Comment by nanliu** [comment]
Thanks!

**Comment by irom77** [comment]
Nan, do you know when catalog will be updated ?

**Comment by nanliu** [comment]
@irom77, we haven't automated the process yet, I'll run another update later today.
